version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "Django"
        # Djangoではメジャー・マイナーバージョンの更新を無視(パッチのみ許可)
        versions: ["~>3.3.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 50
    ignore:
      - dependency-name: "python"
        # Pythonではメジャー・マイナーバージョンの更新を無視(パッチのみ許可)
        versions: ["~>3.10.0"]
  - package-ecosystem: "docker"
    directory: "/.devcontainer/postgresql/"
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    open-pull-requests-limit: 50
