version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "Django"
        # Djangoではバージョン3のマイナーバージョンの更新を無視
        versions: ["3.x"]
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "python"
        # pythonではバージョン3のマイナーバージョンの更新を無視
        versions: ["3.x"]
  # - package-ecosystem: "docker"
  #   directory: "/.devcontainer"
  #   schedule:
  #     interval: "monthly"
  
