version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:20"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    ignore:
      - dependency-name: "Django"
        # Djangoではメジャー・マイナーバージョンの更新を無視(パッチのみ許可)
        update-types:["version-update:semver-major","version-update:semver-minor"]
  # - package-ecosystem: "github-actions"
  #   directory: "/"
  #   schedule:
  #     interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "13:20"
      timezone: "Asia/Tokyo"
    target-branch: "develop"
    ignore:
      - dependency-name: "python"
        # Pythonではメジャー・マイナーバージョンの更新を無視(パッチのみ許可)
        update-types:["version-update:semver-major","version-update:semver-minor"]
  # - package-ecosystem: "docker"
  #   directory: "/.devcontainer"
  #   schedule:
  #     interval: "monthly"
  
